### ISSUE TITLE
Add type 2 file uploads using p2sh scriptSig data space

### ISSUE THREAD

**Issue by jcramer** [simpleledgerinc/BitcoinFilesJS#5]
As defined in the BFP spec, type 2 file uploads represent data storage using p2sh scriptSig.  Current network rules allow each input to contain up to 1650KB of data in scriptSig.  With the 25 transaction chain network policy, we should be able to use this to get files uploaded that are larger than 30KB in size.  This is also a more efficient way to store data, rather than using OP_RETURN space which is currently limited to 220 bytes.

**Comment by projectoblio** [comment]
* Larger than 30MB in size?
